name: Unit Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y gcc-13 g++-13 automake autoconf libtool libfmt-dev

      - name: Build and Run Tests
        run: make test CC=gcc-13 CXX=g++-13 && ./test
